#!/usr/bin/env python3
"""Generate a byte-exact sdas8051 source for a ROM region.

Usage: gen_init.py <rom.bin> <out.a51> <org_hex> <length_dec>

Emits an ABS CODE area at <org> containing the exact ROM bytes as .db
directives. This is the device-under-test for the golden byte-match test;
mnemonic-level documentation lives in src/main.annotated.asm.
"""
import sys


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    rom_path, out_path, org_s, length_s = sys.argv[1:5]
    org = int(org_s, 0)
    length = int(length_s, 0)

    data = open(rom_path, "rb").read()
    chunk = data[org:org + length]
    if len(chunk) != length:
        sys.exit("ERROR: ROM too short for region 0x%04X..len %d" % (org, length))

    out = []
    out.append("; AUTO-GENERATED byte-exact transcription of ROM init region")
    out.append("; Source: %s  bytes 0x%04X..0x%04X" % (rom_path, org, org + length - 1))
    out.append("; Regenerate with: make gen   (do not hand-edit)")
    out.append(";")
    out.append("; Device-under-test for the golden byte-match test. Mnemonic-level")
    out.append("; documentation of the same code lives in src/main.annotated.asm.")
    out.append("")
    out.append("        .area CODE (ABS)")
    out.append("        .org    0x%04X" % org)
    out.append("init_start:")
    for i in range(0, len(chunk), 8):
        row = chunk[i:i + 8]
        out.append("        .db " + ",".join("0x%02x" % b for b in row))
    out.append("init_end:")
    out.append("")
    open(out_path, "w").write("\n".join(out) + "\n")
    print("wrote %s: %d bytes 0x%04X..0x%04X" % (out_path, length, org, org + length - 1))


if __name__ == "__main__":
    main()
