; Generated by disasm51.py
; Copyright (c) 2022 Aleksander Mazur
; https://github.com/OlekMazur/disasm51
;
; Source file: M2764A@DIP28.BIN

cseg
;org	00h
	ljmp jump_05FF

; overlapping 2 byte(s)

org	01h
jump_0001:
	inc @R0
jump_0002:
	nop
	ljmp jump_003F

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	ljmp jump_007F

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	ljmp jump_00BF

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
dptr_001F:
	mov R7, A
	nop
	lcall jump_22FE
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	ljmp jump_02FF

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_003F:
	mov R7, A
	push 0D0h
	setb 0D0h.3
	mov R2, A
	clr A
	mov R1, A
jump_0047:
	mov 83h, #50h	;  80 'P'
	clr A
	movx @DPTR, A
	mov 83h, #52h	;  82 'R'
	movx @DPTR, A
	djnz R1, jump_0047
jump_0052:
	mov R1, #00h	;   0
jump_0054:
	jnb 0B0h.2, jump_0052
	djnz R1, jump_0054
	mov 83h, #50h	;  80 'P'
	mov A, 4Eh
	movx @DPTR, A
	mov 83h, #52h	;  82 'R'
	mov A, 4Fh
	movx @DPTR, A
	mov A, R2
	pop 0D0h
	jbc 28h.3, jump_006E
	setb 20h.1
	reti

jump_006E:
	mov 47h, #0FFh	; 255   -1 'ÿ'
	reti

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_007F:
	mov R7, A
jump_0080:
	mov 8Ah, #11h	;  17
	mov 8Ch, #0E8h	; 232  -24 'è'
	setb 88h.4
	setb 23h.7
	setb 23h.4
	cpl 20h.3
	jnb 20h.3, jump_0093
	setb 20h.4
jump_0093:
	djnz 1Dh, jump_009D
	mov 1Dh, #0Ah	;  10
	setb 23h.6
	setb 23h.5
jump_009D:
	reti

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_00BF:
	mov R7, A
	push 0D0h
	setb 0D0h.3
	mov R2, A
	mov A, R0
	add A, #10h	;  16
	mov R1, A
	jb 22h.7, jump_00D5
	jnb 22h.6, jump_00DC
	mov C, 23h.4
	mov 23h.3, C
	clr 23h.4
jump_00D5:
	mov 83h, #59h	;  89 'Y'
	movx A, @DPTR
	mov @R1, A
	ajmp jump_0278

jump_00DC:
	mov 83h, #58h	;  88 'X'
	rl A
	add A, R1
	add A, #0DEh	; 222  -34 'Þ'
	mov R4, A
	movc A, @A + PC
	xch A, R4
	movc A, @A + PC
	mov 0F0h, A
	movx A, @DPTR
	mov R5, A
	inc 83h
	movx A, @DPTR
	subb A, R4
	jc jump_0118
	mov @R1, A
	mov A, R5
	mov R5, 0F0h
	mul AB
	mov R4, 0F0h
	mov A, @R1
	mov 0F0h, R5
	mul AB
	add A, R4
	rl A
	rl A
	anl A, #03h	;   3
; overlapping 1 byte(s)

org	100h
jump_0100:
	rr A
	mov R4, A
	mov A, 0F0h
	addc A, #00h	;   0
	rlc A
	jc jump_0125
	rlc A
	orl A, R4
	jc jump_012F
	mov @R1, A
	anl 09h, #57h	;  87 'W'
	subb A, @R1
	jnz jump_0136
	mov R4, #00h	;   0
	sjmp jump_0145

jump_0118:
	mov @R1, #00h	;   0
	mov R4, #08h	;   8
	subb A, #0F9h	; 249   -7 'ù'
	mov R6, A
	jz jump_0129
	jc jump_0129
	sjmp jump_0154

jump_0125:
	mov @R1, #0FFh	; 255   -1 'ÿ'
	mov R4, #04h	;   4
jump_0129:
	mov A, #01h	;   1
	mov R6, #0Ah	;  10
	sjmp jump_0154

jump_012F:
	mov @R1, #0FFh	; 255   -1 'ÿ'
	mov R4, #04h	;   4
	inc A
	sjmp jump_0140

jump_0136:
	jc jump_013C
	mov R4, #04h	;   4
	sjmp jump_0140

jump_013C:
	cpl A
	inc A
	mov R4, #08h	;   8
jump_0140:
	cjne A, #0Ah, jump_0143	;  10
jump_0143:
	jnc jump_0129
jump_0145:
	mov R6, A
	add A, #94h	; 148 -108
	movc A, @A + PC
	jbc 0E0h.7, jump_014E
	sjmp jump_0154

jump_014E:
	xch A, 22h
	orl 21h, A
	xch A, 22h
jump_0154:
	jb 20h.0, jump_0159
	ajmp jump_0278

jump_0159:
	mov R5, A
	dec @R0
	mov A, @R0
	anl A, #0Fh	;  15
	jnz jump_01AC
	mov A, R5
	orl A, @R0
	cjne R6, #00h, jump_0167	;   0
	sjmp jump_0198

jump_0167:
	cjne R6, #01h, jump_0171	;   1
	jnb 0E0h.5, jump_0176
	add A, #03h	;   3
	sjmp jump_0198

jump_0171:
	mov A, R4
	swap A
	orl A, R5
	sjmp jump_0198

jump_0176:
	jnb 0E0h.4, jump_017B
	add A, #02h	;   2
jump_017B:
	cjne R4, #04h, jump_0183	;   4
	jb 0E0h.6, jump_0186
	sjmp jump_0194

jump_0183:
	jnb 0E0h.7, jump_0194
jump_0186:
	mov 09h, R0
	xrl 09h, #70h	; 112 'p'
	cjne @R1, #0Fh, jump_019F	;  15
	anl A, #0C0h	; 192  -64 'À'
	orl A, #03h	;   3
	sjmp jump_01A0

jump_0194:
	xrl A, #0C0h	; 192  -64 'À'
	add A, #0Eh	;  14
jump_0198:
	mov 09h, R0
	xrl 09h, #70h	; 112 'p'
	mov @R1, #0FFh	; 255   -1 'ÿ'
jump_019F:
	inc @R1
jump_01A0:
	mov @R0, A
	mov A, R0
	jbc 0E0h.2, jump_01B4
jump_01A5:
	mov 83h, #50h	;  80 'P'
	mov R1, #4Eh	;  78 'N'
	sjmp jump_01B9

jump_01AC:
	mov R4, #00h	;   0
	mov A, R0
	jnb 0E0h.2, jump_01A5
	clr 0E0h.2
jump_01B4:
	mov 83h, #52h	;  82 'R'
	mov R1, #4Fh	;  79 'O'
jump_01B9:
	mov R5, A
	movc A, @A + PC
	anl A, @R1
	mov @R1, A
	mov A, R4
	add A, R5
	movc A, @A + PC
	orl A, @R1
	mov @R1, A
	movx @DPTR, A
	mov A, 22h
	anl A, 2Bh
	jnz jump_0214
	ajmp jump_0278

	addc A, R0
	nop
	mov R4, #50h	;  80 'P'
	nop
	clr 29h.1
	nop
	xch A, R5
	dec @R1
	nop
	anl A, #18h	;  24
	nop
	anl 70h, #00h	;   0
	mov R2, A
	anl C, 80h.5
	div AB
	rr A
	rr A
	ljmp jump_0100

	ajmp jump_0001

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	addc A, R7
	xch A, R7
	movx @R1, A
	mov R4, A
	nop
	nop
	nop
	nop
	nop
	jc jump_021E
	inc A
	ajmp jump_0080

	jb 21h.0, jump_0216
jump_0214:
	anl A, 2Ch
jump_0216:
	jnz jump_0246
	jnb 23h.3, jump_0278
	mov A, R0
	orl A, #78h	; 120 'x'
jump_021E:
	mov R1, A
	dec @R1
	cjne @R1, #00h, jump_0278	;   0
	anl 09h, #77h	; 119 'w'
	mov A, @R1
	orl 09h, #78h	; 120 'x'
	mov @R1, A
	anl 09h, #57h	;  87 'W'
	mov A, 22h
	anl A, 2Dh
	jz jump_0237
	inc @R1
	sjmp jump_0238

jump_0237:
	dec @R1
jump_0238:
	mov A, @R1
	anl 09h, #47h	;  71 'G'
	xrl A, @R1
	jnz jump_0278
	mov A, 22h
	cpl A
	anl 2Bh, A
	sjmp jump_0278

jump_0246:
	cpl A
	anl 2Ch, A
	mov A, R0
	anl A, #47h	;  71 'G'
	mov R1, A
	mov A, @R1
	mov R4, A
	orl 09h, #50h	;  80 'P'
	subb A, @R1
	jz jump_0260
	orl 09h, #70h	; 112 'p'
	mov A, @R1
	jnz jump_0269
	anl 09h, #57h	;  87 'W'
	mov @R1, 0Ch
jump_0260:
	mov A, 22h
	cpl A
	anl 2Bh, A
	anl 21h, A
	sjmp jump_0278

jump_0269:
	orl 09h, #78h	; 120 'x'
	mov @R1, A
	mov A, 22h
	jc jump_0275
	orl 2Dh, A
	sjmp jump_0278

jump_0275:
	cpl A
	anl 2Dh, A
jump_0278:
	mov A, 22h
	rl A
	mov 22h, A
	mov A, R0
	inc A
	anl A, #07h	;   7
	mov 83h, #58h	;  88 'X'
	movx @DPTR, A
	orl A, #48h	;  72 'H'
	mov R0, A
	mov A, R2
	pop 0D0h
	reti

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_02FF:
	mov R7, A
	push 0D0h
	setb 0D0h.4
	mov R7, A
	jnb 98h.0, fwd_0352_jump_0525
	clr 98h.0
	mov A, 99h
	mov 18h, #14h	;  20
	setb 24h.2
	jb 24h.0, jump_0354
	setb 24h.0
	mov R6, A
	mov R0, #60h	;  96 '`'
	mov R2, #01h	;   1
	jb 0E0h.7, jump_033F
	jb 0E0h.6, jump_032D
	jb 0E0h.4, fwd_0352_jump_0525
	anl A, #07h	;   7
	cjne A, #07h, fwd_0352_jump_0525	;   7
	mov R2, #06h	;   6
	ajmp jump_0525

jump_032D:
	jnb 0E0h.5, jump_039F
	jnb 0E0h.4, jump_039F
	inc R2
	anl A, #07h	;   7
	cjne A, #07h, fwd_0352_jump_0525	;   7
	setb 24h.3
	mov R2, #06h	;   6
	ajmp jump_0525

jump_033F:
	cjne A, #81h, jump_0346	; 129 -127
	setb 24h.3
	ajmp jump_0525

jump_0346:
	add A, #77h	; 119 'w'
	jc jump_0350
	add A, #02h	;   2
	jnc jump_039F
	ajmp jump_0525

jump_0350:
	clr 24h.0
fwd_0352_jump_0525:
	ajmp jump_0525

jump_0354:
	jbc 24h.1, jump_03A9
	cjne R6, #81h, jump_0398	; 129 -127
	jbc 24h.3, jump_037B
	jbc 24h.4, jump_0380
	mov 83h, 31h
	mov 82h, 30h
	movx @DPTR, A
	inc 30h
	mov A, 30h
	jnz jump_036F
	inc 31h
jump_036F:
	djnz R0, fwd_03A1_jump_0525
	djnz R2, fwd_03A1_jump_0525
	movx A, @DPTR
	cjne A, #83h, jump_039F	; 131 -125
	setb 28h.1
	sjmp jump_039F

jump_037B:
	mov R0, A
	setb 24h.4
	ajmp jump_0525

jump_0380:
	mov R2, A
	mov 30h, #00h	;   0
	mov 31h, 3Fh
	mov 83h, 3Eh
	mov 82h, #0FFh	; 255   -1 'ÿ'
	movx @DPTR, A
	dec 82h
	mov A, R0
	dec A
	movx @DPTR, A
	clr 28h.1
	inc R2
	ajmp jump_0525

jump_0398:
	mov @R0, A
	inc R0
	djnz R2, fwd_03A1_jump_0525
	jbc 24h.3, jump_03A3
jump_039F:
	setb 24h.1
fwd_03A1_jump_0525:
	ajmp jump_0525

jump_03A3:
	mov R2, #06h	;   6
	mov R0, #70h	; 112 'p'
	ajmp jump_0525

jump_03A9:
	anl 24h, #0C0h	; 192  -64 'À'
	mov R4, #0F3h	; 243  -13 'ó'
	cjne A, #03h, jump_03C1	;   3
	mov A, R6
	mov R5, A
	jnb 0E0h.7, fwd_03C7_jump_0440
	inc R4
	subb A, #80h	; 128 -128
	mov R6, A
	jnz jump_03E1
	jb 28h.1, jump_03C9
jump_03BF:
	clr 28h.1
jump_03C1:
	setb 25h.3
	clr 25h.2
	ajmp jump_0525

fwd_03C7_jump_0440:
	ajmp jump_0440

jump_03C9:
	setb 25h.6
	mov 83h, 3Eh
	mov 82h, #0FEh	; 254   -2 'þ'
	movx A, @DPTR
	add A, #04h	;   4
	mov R1, A
	inc DPTR
	movx A, @DPTR
	mov R3, A
	inc R3
	mov 30h, #0FDh	; 253   -3 'ý'
	mov 31h, 3Eh
	ajmp jump_0525

jump_03E1:
	djnz R6, jump_03F1
	jnb 28h.0, jump_03BF
	lcall jump_07FF
	inc R4
	jnb 28h.1, jump_03C1
jump_03ED:
	setb 25h.2
	ajmp jump_0525

jump_03F1:
	mov R4, #0F6h	; 246  -10 'ö'
	jnb 28h.1, jump_03C1
	djnz R6, jump_040B
	clr A
	mov 26h, A
	mov 66h, A
	mov 67h, 3Fh
jump_0400:
	lcall jump_0802
	jnb 28h.1, jump_03C1
	mov 1Fh, #0FFh	; 255   -1 'ÿ'
	sjmp jump_041A

jump_040B:
	djnz R6, jump_0415
jump_040D:
	anl 28h, #03h	;   3
	mov 26h, #00h	;   0
	sjmp jump_03ED

jump_0415:
	djnz R6, jump_041F
	jnb 28h.2, jump_03C1
jump_041A:
	orl 28h, #0Ch	;  12
	sjmp jump_03ED

jump_041F:
	djnz R6, jump_0428
	jnb 28h.2, jump_03C1
	setb 28h.4
	sjmp jump_03ED

jump_0428:
	djnz R6, jump_042E
	clr 28h.3
	sjmp jump_03ED

jump_042E:
	mov A, 60h
	djnz R6, jump_0437
	lcall jump_0A33
	sjmp jump_0400

jump_0437:
	mov R4, #0F2h	; 242  -14 'ò'
	djnz R6, jump_03C1
	lcall jump_0A33
	sjmp jump_040D

jump_0440:
	jnb 0E0h.6, jump_04AF
	jb 0E0h.5, jump_048C
	mov R1, #68h	; 104 'h'
	mov @R1, A
	mov R3, #01h	;   1
	jb 0E0h.4, jump_0471
	anl A, #07h	;   7
	cjne A, #07h, jump_0469	;   7
	mov 69h, 58h
	mov 6Ah, 59h
	mov 6Bh, 5Ah
	mov 6Ch, 5Bh
	mov 6Dh, 5Ch
	mov 6Eh, 5Dh
	mov R3, #07h	;   7
	ajmp jump_0486

jump_0469:
	add A, #58h	;  88 'X'
	mov R0, A
	mov 69h, @R0
	inc R3
	ajmp jump_0486

jump_0471:
	jnb 0E0h.0, jump_0478
	inc R1
	inc R3
	mov @R1, 5Eh
jump_0478:
	jnb 0E0h.1, jump_047F
	inc R1
	inc R3
	mov @R1, 5Fh
jump_047F:
	jnb 0E0h.2, jump_0486
	inc R1
	inc R3
	mov @R1, 90h
jump_0486:
	setb 25h.1
	mov R1, #68h	; 104 'h'
	ajmp jump_0525

jump_048C:
	jb 0E0h.4, jump_04D5
	jb 0E0h.1, jump_0498
	mov C, 0E0h.0
	mov 20h.0, C
	ajmp jump_0525

jump_0498:
	jb 0E0h.0, jump_050B
	mov 50h, 58h
	mov 51h, 59h
	mov 52h, 5Ah
	mov 53h, 5Bh
	mov 54h, 5Ch
	mov 55h, 5Dh
	ajmp jump_0525

jump_04AF:
	jb 0E0h.4, jump_051F
	anl A, #07h	;   7
	cjne A, #07h, jump_04CE	;   7
	mov 21h, #00h	;   0
	mov 50h, 60h
	mov 51h, 61h
	mov 52h, 62h
	mov 53h, 63h
	mov 54h, 64h
	mov 55h, 65h
	sjmp jump_04FF

jump_04CE:
	add A, #50h	;  80 'P'
	mov R0, A
	mov @R0, 60h
	sjmp jump_04FF

jump_04D5:
	anl A, #07h	;   7
	cjne A, #07h, jump_04F0	;   7
	mov 40h, 60h
	mov 41h, 61h
	mov 42h, 62h
	mov 43h, 63h
	mov 44h, 64h
	mov 45h, 65h
	mov A, #3Fh	;  63 '?'
	sjmp jump_04FB

jump_04F0:
	add A, #40h	;  64 '@'
	mov R0, A
	mov @R0, 60h
	orl 10h, #70h	; 112 'p'
	mov @R0, 61h
	movc A, @A + PC
jump_04FB:
	orl 2Bh, A
	orl 2Ch, A
jump_04FF:
	mov A, R6
	mov C, 0E0h.3
	mov 23h.1, C
jump_0504:
	setb 25h.7
	mov 19h, #64h	; 100 'd'
	ajmp jump_0525

jump_050B:
	mov 68h, A
	mov DPTR, #dptr_001F
	movx A, @DPTR
	mov 69h, A
	inc DPTR
	movx A, @DPTR
	mov 6Ah, A
	inc DPTR
	movx A, @DPTR
	mov 6Bh, A
	mov R3, #04h	;   4
	ajmp jump_0486

jump_051F:
	mov R0, 60h
	acall jump_07D0
	mov 47h, A
jump_0525:
	jnb 98h.1, jump_052C
	clr 98h.1
	acall jump_0541
jump_052C:
	mov A, R7
	pop 0D0h
	reti

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	ajmp jump_0002

	inc A
	inc R0
	jbc 24h.0, jump_0504
; overlapping 1 byte(s)

org	541h
jump_0541:
	clr 23h.0
	jnb 25h.1, jump_0557
	jbc 25h.4, jump_0551
	mov 99h, @R1
	inc R1
	djnz R3, jump_0550
	setb 25h.4
jump_0550:
	ret

jump_0551:
	clr 25h.1
jump_0553:
	mov 99h, #03h	;   3
	ret

jump_0557:
	jb 25h.6, jump_056E
	jbc 25h.2, jump_0569
	jbc 25h.5, jump_0553
	jbc 25h.3, jump_0566
	setb 23h.0
	ret

jump_0566:
	mov 99h, R4
	ret

jump_0569:
	mov 99h, R5
	setb 25h.5
	ret

jump_056E:
	mov 82h, 30h
	mov 83h, 31h
	movx A, @DPTR
	mov 99h, A
	inc 30h
	mov A, 30h
	jnz jump_057F
	inc 31h
jump_057F:
	djnz R1, jump_0587
	djnz R3, jump_0587
	clr 25h.6
	setb 25h.5
jump_0587:
	ret

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_05FF:
	mov R7, A
	mov A, #78h	; 120 'x'
jump_0602:
	djnz R0, $
	djnz 0E0h, jump_0602
	mov 83h, #48h	;  72 'H'
jump_060A:
	movx @DPTR, A
	djnz R0, jump_060A
	djnz R0, $
	mov 83h, #53h	;  83 'S'
	mov A, #80h	; 128 -128
	movx @DPTR, A
	clr A
	dec 83h
	movx @DPTR, A
	dec 83h
	mov A, #0FFh	; 255   -1 'ÿ'
	movx @DPTR, A
	dec 83h
	clr A
	movx @DPTR, A
	mov 83h, #59h	;  89 'Y'
	mov A, #01h	;   1
	movx @DPTR, A
	mov R0, #7Fh	; 127
	clr A
	mov 0D0h, A
jump_062D:
	mov @R0, A
	djnz R0, jump_062D
	mov 81h, #31h	;  49 '1'
	mov 47h, #0FFh	; 255   -1 'ÿ'
	mov 1Fh, #0FFh	; 255   -1 'ÿ'
	mov DPTR, #dptr_7FFF
jump_063C:
	movx A, @DPTR
	cpl A
	movx @DPTR, A
	mov R0, A
	movx A, @DPTR
	xrl A, R0
	jz jump_064E
	jbc 28h.7, jump_0672
	setb 28h.7
	mov 83h, #0A0h	; 160  -96
	sjmp jump_063C

jump_064E:
	mov A, R0
	cpl A
	movx @DPTR, A
	mov 3Eh, 83h
	mov 3Fh, 3Eh
	inc 3Fh
	mov 28h, #03h	;   3
	mov 82h, #0F0h	; 240  -16 'ð'
	mov R0, #08h	;   8
jump_0661:
	movx A, @DPTR
	cjne A, 00h, jump_0667
	sjmp jump_066C

jump_0667:
	mov A, 00h
	movx @DPTR, A
	clr 28h.1
jump_066C:
	inc DPTR
	djnz R0, jump_0661
	lcall jump_07FF
jump_0672:
	mov 08h, #48h	;  72 'H'
	mov 22h, #01h	;   1
	mov 83h, #58h	;  88 'X'
	clr A
	movx @DPTR, A
	mov 0A8h, #84h	; 132 -124
	jb 22h.0, $
	jnb 22h.0, $
	clr 0A8h.7
	mov R7, #06h	;   6
	mov R0, #58h	;  88 'X'
	mov R1, #50h	;  80 'P'
jump_068E:
	mov A, @R0
	mov @R1, A
	inc R0
	inc R1
	djnz R7, jump_068E
	mov R7, #06h	;   6
	mov R0, #48h	;  72 'H'
	mov A, #01h	;   1
jump_069A:
	mov @R0, A
	inc R0
	djnz R7, jump_069A
	mov 89h, #21h	;  33 '!'
	mov 88h, #00h	;   0
	mov 98h, #50h	;  80 'P'
	jb 0B0h.0, jump_06B1
	mov 0A8h, #07h	;   7
	setb 20h.2
	ajmp jump_073C

jump_06B1:
	jb 0B0h.2, jump_06B6
	setb 20h.2
jump_06B6:
	clr A
	mov 88h, A
	mov 8Ah, A
	mov 8Ch, A
	mov R0, #01h	;   1
	jb 0B0h.0, $
	setb 88h.4
jump_06C4:
	jb 88h.5, jump_06B6
	jnb 0B0h.0, jump_06C4
	acall jump_06E4
jump_06CC:
	jb 88h.5, jump_06B6
	jb 0B0h.0, jump_06CC
	acall jump_06E4
jump_06D4:
	jb 88h.5, jump_06B6
	jnb 0B0h.0, jump_06D4
	acall jump_06E4
jump_06DC:
	jb 88h.5, jump_06F3
	jb 0B0h.0, jump_06DC
	sjmp jump_06B6

jump_06E4:
	clr 88h.4
	mov @R0, 8Ah
	inc R0
	mov @R0, 8Ch
	mov 8Ah, A
	mov 8Ch, A
	setb 88h.4
	inc R0
	ret

jump_06F3:
	mov R7, #01h	;   1
jump_06F5:
	mov A, R2
	jz jump_070A
	mov R0, #06h	;   6
jump_06FA:
	clr C
	mov A, @R0
	rrc A
	mov @R0, A
	dec R0
	mov A, @R0
	rrc A
	mov @R0, A
	djnz R0, jump_06FA
	clr C
	mov A, R7
	rlc A
	mov R7, A
	sjmp jump_06F5

jump_070A:
	mov A, R1
	mov 0F0h, #06h	;   6
	div AB
	add A, #08h	;   8
	anl A, #0F0h	; 240  -16 'ð'
	cjne A, #20h, jump_06B6	;  32 ' '
	mov A, R3
	add A, #08h	;   8
	anl A, #0F0h	; 240  -16 'ð'
	cjne A, #20h, jump_06B6	;  32 ' '
	mov A, R5
	clr C
	rrc A
	add A, #08h	;   8
	anl A, #0F0h	; 240  -16 'ð'
	cjne A, #20h, jump_06B6	;  32 ' '
	mov A, R7
	dec A
	cpl A
	mov 8Dh, A
	setb 88h.6
	mov 99h, #15h	;  21
	jnb 98h.1, $
	clr 98h.1
	setb 23h.0
	mov 0A8h, #17h	;  23
jump_073C:
	mov 1Dh, #0Ah	;  10
	mov 8Ch, #0E8h	; 232  -24 'è'
	setb 88h.4
	setb 20h.0
	clr A
	mov 83h, #58h	;  88 'X'
	movx @DPTR, A
	setb 0A8h.7
jump_074D:
	clr 0A8h.7
	setb 0D0h.4
	jnb 25h.7, jump_0780
	mov A, 21h
	cjne A, #3Fh, jump_0763	;  63 '?'
	mov A, 2Bh
	jnz jump_0780
	mov C, 23h.1
	mov 25h.2, C
	sjmp jump_077E

jump_0763:
	jnb 23h.6, jump_0780
	clr 23h.6
	djnz 19h, jump_0780
	clr 20h.0
	clr A
	mov 83h, #50h	;  80 'P'
	movx @DPTR, A
	mov 4Eh, A
	mov 83h, #52h	;  82 'R'
	movx @DPTR, A
	mov 4Fh, A
	mov R4, #0F7h	; 247   -9 '÷'
	setb 25h.3
jump_077E:
	clr 25h.7
jump_0780:
	jnb 23h.0, jump_0785
	acall jump_0541
jump_0785:
	jnb 23h.7, jump_0797
	clr 23h.7
	jnb 24h.2, jump_0797
	djnz 18h, jump_0797
	anl 24h, #0F0h	; 240  -16 'ð'
	mov R4, #0F1h	; 241  -15 'ñ'
	setb 25h.3
jump_0797:
	clr 0D0h.4
	lcall jump_08FF
	setb 0A8h.7
	jnb 20h.4, jump_074D
	jnb 20h.2, jump_074D
	clr 20h.4
	jb 28h.3, jump_074D
	clr 0A8h.7
	jb 0B0h.4, jump_07C4
	clr A
	mov 26h, A
	mov 66h, A
	mov 67h, 3Fh
	lcall jump_0802
	jnb 28h.1, jump_07CC
	mov 1Fh, #0FFh	; 255   -1 'ÿ'
	orl 28h, #0Ch	;  12
	sjmp jump_07CC

jump_07C4:
	lcall jump_0BFF
	jz jump_07CC
	lcall jump_0C7F
jump_07CC:
	setb 0A8h.7
	ajmp jump_074D

jump_07D0:
	anl A, #03h	;   3
jump_07D2:
	mov R2, A
	mov A, 1Fh
	djnz R2, jump_07DA
	orl A, R0
	sjmp jump_07E5

jump_07DA:
	djnz R2, jump_07DF
	anl A, R0
	sjmp jump_07E5

jump_07DF:
	djnz R2, jump_07E4
	xrl A, R0
	sjmp jump_07E5

jump_07E4:
	mov A, R0
jump_07E5:
	mov 7Fh, 83h
	mov 83h, #51h	;  81 'Q'
	mov 1Fh, A
	movx @DPTR, A
	mov 83h, 7Fh
	ret

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_07FF:
	mov R7, A
	jnb 28h.1, jump_0880
; overlapping 1 byte(s)

org	802h
jump_0802:
	mov R5, #0D2h	; 210  -46 'Ò'
; overlapping 1 byte(s)

org	803h
jump_0803:
	setb 28h.1
	mov 83h, 3Eh
	mov 82h, #0EEh	; 238  -18 'î'
jump_080B:
	clr A
	movx @DPTR, A
	dec 82h
	mov A, 3Fh
	movx @DPTR, A
	djnz 82h, jump_080B
	clr A
	movx @DPTR, A
	mov 82h, #0FEh	; 254   -2 'þ'
	movx A, @DPTR
	mov 7Eh, A
	mov 76h, A
	anl A, #07h	;   7
	jnz jump_0880
	inc DPTR
	movx A, @DPTR
	mov 7Fh, A
	orl A, 7Eh
	jz jump_0880
	mov A, 3Fh
	add A, 7Fh
	mov 77h, A
	mov 83h, A
	mov 82h, 7Eh
	movx A, @DPTR
	cjne A, #83h, jump_0880	; 131 -125
jump_083A:
	mov A, #0F8h	; 248   -8 'ø'
jump_083C:
	add A, 82h
	mov 82h, A
	jnc jump_084E
	jnz jump_0850
	mov A, 83h
	cjne A, 3Fh, jump_0850
	movx A, @DPTR
	jb 0E0h.7, jump_0880
	ret

jump_084E:
	dec 83h
jump_0850:
	movx A, @DPTR
	jb 0E0h.7, jump_0880
	cjne A, #36h, jump_0860	;  54 '6'
	inc DPTR
	inc DPTR
	inc DPTR
	clr A
	movx @DPTR, A
	mov A, #0F5h	; 245  -11 'õ'
	sjmp jump_083C

jump_0860:
	cjne A, #1Fh, jump_083A	;  31
	inc DPTR
	movx A, @DPTR
	rl A
	dec 82h
	xch A, 82h
	mov 7Eh, A
	mov 7Fh, 83h
	mov 83h, 3Eh
	movx @DPTR, A
	inc DPTR
	mov A, 7Fh
	movx @DPTR, A
	mov 83h, A
	mov 82h, 7Eh
	sjmp jump_083A

	mov R7, A
	mov R7, A
jump_0880:
	anl 28h, #01h	;   1
	mov 82h, #0FDh	; 253   -3 'ý'
	mov 83h, 3Eh
	mov A, #80h	; 128 -128
	movx @DPTR, A
	inc DPTR
	clr A
	mov 76h, A
	mov 77h, 3Fh
	movx @DPTR, A
	inc DPTR
	movx @DPTR, A
	inc DPTR
	mov A, #83h	; 131 -125
	movx @DPTR, A
	ret

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_08FF:
	mov R7, A
	jb 28h.4, jump_0906
	jnb 28h.3, jump_0940
jump_0906:
	mov 83h, #51h	;  81 'Q'
	mov A, 1Fh
	movx @DPTR, A
	mov A, 26h
	jz jump_0941
	jnb 0E0h.0, jump_091E
	mov A, 21h
	cjne A, #3Fh, jump_0940	;  63 '?'
	mov A, 2Bh
	jnz jump_0940
	sjmp jump_093B

jump_091E:
	jnb 0E0h.1, jump_092E
	jnb 23h.5, jump_0940
	clr 23h.5
	djnz 1Ah, jump_0940
	djnz 1Bh, jump_0940
	sjmp jump_093B

jump_092E:
	mov A, 90h
	jnb 27h.0, jump_0937
	anl A, R7
	jz jump_093B
	ret

jump_0937:
	orl A, R7
	cjne A, #0FFh, jump_0940	; 255   -1 'ÿ'
jump_093B:
	mov 26h, #00h	;   0
	clr 28h.4
jump_0940:
	ret

jump_0941:
	clr 28h.4
	mov 82h, 66h
	mov 83h, 67h
	movx A, @DPTR
	mov R0, A
	mov 27h, A
jump_094D:
	jnb 0E0h.7, jump_0954
	anl 28h, #03h	;   3
	ret

jump_0954:
	jnb 0E0h.6, jump_09A9
	jnb 0E0h.5, jump_099A
	inc DPTR
	mov C, 0E0h.3
	mov 26h.0, C
	mov 28h.4, C
	anl A, #07h	;   7
	cjne A, #07h, jump_0982	;   7
	mov R0, #40h	;  64 '@'
	mov R7, #06h	;   6
jump_096A:
	movx A, @DPTR
	mov @R0, A
	inc DPTR
	inc R0
	djnz R7, jump_096A
	inc DPTR
	inc DPTR
	mov R0, #70h	; 112 'p'
	mov R7, #06h	;   6
jump_0976:
	movx A, @DPTR
	mov @R0, A
	inc DPTR
	inc R0
	djnz R7, jump_0976
	mov A, #3Fh	;  63 '?'
	mov R7, #10h	;  16
	sjmp jump_0993

jump_0982:
	add A, #40h	;  64 '@'
	mov R0, A
	movx A, @DPTR
	mov @R0, A
	orl 00h, #70h	; 112 'p'
	inc DPTR
	movx A, @DPTR
	mov @R0, A
	mov R7, #08h	;   8
	mov A, R0
	anl A, #17h	;  23
	movc A, @A + PC
jump_0993:
	orl 2Bh, A
	orl 2Ch, A
	mov A, R7
	sjmp jump_0A03

jump_099A:
	anl 28h, #07h	;   7
	sjmp jump_0A01

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	ajmp jump_0802

	inc A
	inc R0
	jbc 24h.0, jump_094D
; overlapping 1 byte(s)

org	9A9h
jump_09A9:
	inc DPTR
	jb 0E0h.5, jump_09F1
	jb 0E0h.4, jump_09D1
	mov 21h, #00h	;   0
	mov C, 0E0h.3
	mov 26h.0, C
	mov 28h.4, C
	anl A, #07h	;   7
	cjne A, #07h, jump_09C4	;   7
	mov R0, #50h	;  80 'P'
	mov R7, #06h	;   6
	sjmp jump_09C9

jump_09C4:
	add A, #50h	;  80 'P'
	mov R0, A
	mov R7, #01h	;   1
jump_09C9:
	movx A, @DPTR
	mov @R0, A
	inc DPTR
	inc R0
	djnz R7, jump_09C9
	sjmp jump_0A01

jump_09D1:
	jb 0E0h.3, jump_09DE
	anl A, #03h	;   3
	mov R2, A
	movx A, @DPTR
	mov R0, A
	lcall jump_07D2
	sjmp jump_0A01

jump_09DE:
	jb 0E0h.2, fwd_09EF_jump_0A01
	setb 26h.1
	setb 28h.4
	movx A, @DPTR
	mov 1Ah, A
	inc DPTR
	movx A, @DPTR
	inc A
	mov 1Bh, A
	sjmp jump_0A01

fwd_09EF_jump_0A01:
	sjmp jump_0A01

jump_09F1:
	jnb 0E0h.4, jump_0A01
	jb 0E0h.3, jump_0A01
	add A, #0CEh	; 206  -50 'Î'
	jc jump_0A0C
	movx A, @DPTR
	mov R7, A
	setb 26h.2
	setb 28h.4
jump_0A01:
	mov A, #08h	;   8
jump_0A03:
	add A, 66h
	mov 66h, A
	jnc jump_0A0B
	inc 67h
jump_0A0B:
	ret

jump_0A0C:
	movx A, @DPTR
	mov R0, A
	inc DPTR
	jb 27h.2, jump_0A23
	movx A, @DPTR
	jnb 27h.0, jump_0A1C
	anl A, 90h
	jnz jump_0A01
	sjmp jump_0A33

jump_0A1C:
	orl A, 90h
	cjne A, #0FFh, jump_0A01	; 255   -1 'ÿ'
	sjmp jump_0A33

jump_0A23:
	jnb 27h.1, jump_0A34
	movx A, @DPTR
	mov R7, A
	inc DPTR
	movx A, @DPTR
	inc A
	cjne A, 07h, jump_0A32
	clr A
	movx @DPTR, A
	sjmp jump_0A01

jump_0A32:
	movx @DPTR, A
jump_0A33:
	mov A, R0
jump_0A34:
	rl A
	mov 82h, A
	mov 83h, 3Eh
	movx A, @DPTR
	mov 66h, A
	inc DPTR
	movx A, @DPTR
	mov 67h, A
	ret

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_0A85:
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_0BFF:
	mov R7, A
	jbc 20h.1, jump_0C64
	mov 83h, #51h	;  81 'Q'
	mov R6, #00h	;   0
	mov A, 47h
	anl A, #0Fh	;  15
jump_0C0C:
	movx @DPTR, A
	mov 46h, A
	mov A, 90h
	anl A, #0E0h	; 224  -32 'à'
	jz jump_0C2F
	jb 0E0h.5, jump_0C1C
	swap A
	rl A
	sjmp jump_0C20

jump_0C1C:
	anl A, #0C0h	; 192  -64 'À'
	jnz jump_0C4E
jump_0C20:
	xch A, R6
	jnz jump_0C4E
	mov A, 46h
	swap A
	anl A, #07h	;   7
	inc A
	add A, R6
	mov R6, A
	add A, #0E7h	; 231  -25 'ç'
	jc jump_0C4E
jump_0C2F:
	mov A, 46h
	add A, #10h	;  16
	jnb 0E0h.7, jump_0C0C
	mov A, 47h
	movx @DPTR, A
	mov A, R6
	xch A, 56h
	cjne A, 56h, jump_0C56
	jz jump_0C5D
	jnb 20h.6, jump_0C5F
	jnb 20h.5, jump_0C61
	djnz 57h, jump_0C5F
	mov 57h, #03h	;   3
	ret

jump_0C4E:
	mov 56h, #0FFh	; 255   -1 'ÿ'
	mov A, 47h
	movx @DPTR, A
	sjmp jump_0C5F

jump_0C56:
	clr 20h.5
	mov 57h, #23h	;  35 '#'
	sjmp jump_0C5F

jump_0C5D:
	setb 20h.6
jump_0C5F:
	clr A
	ret

jump_0C61:
	clr 20h.6
	ret

jump_0C64:
	mov A, #19h	;  25
; overlapping 1 byte(s)

org	0C65h
jump_0C65:
	dec R1
	mov R6, A
	mov 56h, A
	clr 20h.6
	ret

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_0C7F:
	mov R7, A
	dec A
	cjne A, #0Eh, jump_0C8D	;  14
jump_0C84:
	clr A
	mov 6Dh, A
	mov 2Ah, A
	orl 47h, #0F8h	; 248   -8 'ø'
	ret

jump_0C8D:
	jb 2Ah.7, jump_0CEA
	jb 2Ah.6, jump_0CB1
	setb 2Ah.7
	cjne A, #0Ah, jump_0CA1	;  10
	mov R3, #20h	;  32 ' '
	mov 29h, #20h	;  32 ' '
	anl 47h, #0F7h	; 247   -9 '÷'
	ret

jump_0CA1:
	jnc jump_0CB2
jump_0CA3:
	dec A
	cjne A, #06h, jump_0CA7	;   6
jump_0CA7:
	jnc jump_0D23
	setb 2Ah.5
	add A, #50h	;  80 'P'
	mov R1, A
	mov 29h, #40h	;  64 '@'
jump_0CB1:
	ret

jump_0CB2:
	inc A
	jnb 0E0h.4, jump_0D23
	add A, R6
	add A, R6
	subb A, #28h	;  40 '('
	mov 29h, A
	add A, #02h	;   2
	mov R3, A
	inc A
	movc A, @A + PC
	xch A, R3
	movc A, @A + PC
	xch A, 29h
	movc A, @A + PC
	anl 47h, #0Fh	;  15
	orl 47h, A
	ret

	mov 0A0h, R0
	movx @DPTR, A
	mov 0A0h, R4
	movx @DPTR, A
	lcall jump_890F
	inc R7
	add A, R3
	jb 23h.1, jump_0CF2
	jnb 23h.7, jump_0CED
	jc jump_0D13
	lcall jump_502F
	inc R2
	jz jump_0C65
	anl C, /2Eh.0
	div AB
	anl C, /0F0h.0
jump_0CEA:
	cjne A, #0Ah, jump_0D10	;  10
jump_0CED:
	jnb 29h.7, jump_0D23
	clr 2Ah.1
jump_0CF2:
	mov A, R3
	xrl A, #02h	;   2
	mov R3, A
	anl 47h, #0F7h	; 247   -9 '÷'
	jnb 2Ah.2, jump_0D03
	mov 6Ch, 6Dh
	mov 29h, #10h	;  16
	ret

jump_0D03:
	mov 29h, #30h	;  48 '0'
	cjne A, #10h, jump_0D0F	;  16
	mov 29h, #08h	;   8
	mov 47h, 1Fh
jump_0D0F:
	ret

jump_0D10:
	jnc jump_0D8E
	jb 2Ah.5, jump_0CA3
; overlapping 2 byte(s)

org	0D13h
jump_0D13:
	anl A, 8Eh
	jb 2Ah.1, jump_0D65
	setb 2Ah.2
	mov 6Eh, #00h	;   0
	jb 29h.4, jump_0D42
	jbc 29h.3, jump_0D2A
jump_0D23:
	mov 2Ah, #40h	;  64 '@'
	anl 47h, #0Fh	;  15
	ret

jump_0D2A:
	jz jump_0D23
	cjne A, #09h, jump_0D2F	;   9
jump_0D2F:
	jnc jump_0D23
	mov R4, A
	cjne R3, #10h, jump_0D3B	;  16
	clr 2Ah.2
	mov 29h, #48h	;  72 'H'
	ret

jump_0D3B:
	acall jump_0FC4
	cpl A
	mov 6Dh, A
	sjmp jump_0D4D

jump_0D42:
	mov 6Dh, A
	jnz jump_0D4B
	anl 29h, #0E7h	; 231  -25 'ç'
	sjmp jump_0D4D

jump_0D4B:
	setb 2Ah.1
jump_0D4D:
	jb 29h.0, jump_0D56
	jb 29h.1, jump_0D5D
	setb 29h.5
	ret

jump_0D56:
	jb 29h.1, jump_0D61
	mov 29h, #40h	;  64 '@'
	ret

jump_0D5D:
	orl 29h, #0A0h	; 160  -96
	ret

jump_0D61:
	mov 29h, #80h	; 128 -128
	ret

jump_0D65:
	mov R6, A
	mov A, 6Dh
	mov 0F0h, #0Ah	;  10
	mul AB
	jb 29h.3, jump_0D78
	jb 0D0h.2, jump_0D23
	add A, R6
	jc jump_0D23
	mov 6Dh, A
	ret

jump_0D78:
	add A, R6
	mov 6Dh, A
	clr A
	addc A, 0F0h
	mov R6, A
	mov A, 6Eh
	mov 0F0h, #0Ah	;  10
	mul AB
	jb 0D0h.2, jump_0D23
	add A, R6
	jc jump_0D23
	mov 6Eh, A
	ret

jump_0D8E:
	cjne A, #0Dh, jump_0DF4	;  13
	jnb 29h.5, jump_0D23
	mov A, R3
	jb 0E0h.7, fwd_0DF2_jump_0EC0
	cjne A, #0Dh, jump_0DA5	;  13
	mov A, R4
	add A, #4Fh	;  79 'O'
	mov R1, A
	mov @R1, 6Dh
	acall jump_0E38
	ajmp jump_0C84

jump_0DA5:
	mov 82h, 66h
	mov 83h, 67h
	movx @DPTR, A
	inc DPTR
	mov R1, #6Ch	; 108 'l'
	mov R6, #01h	;   1
	jb 0E0h.5, jump_0DBD
	jb 0E0h.4, jump_0DCD
	mov R1, #50h	;  80 'P'
	mov R6, #06h	;   6
	sjmp jump_0DDB

jump_0DBD:
	jb 0E0h.1, jump_0DC4
	mov A, 6Dh
	sjmp jump_0DDC

jump_0DC4:
	inc R6
	jb 0E0h.2, jump_0DDA
	mov A, 6Dh
	dec R1
	sjmp jump_0DDC

jump_0DCD:
	cjne A, #10h, jump_0DD6	;  16
	mov A, 47h
	mov 1Fh, A
	sjmp jump_0DDC

jump_0DD6:
	inc R1
	cjne A, #19h, jump_0DDB	;  25
jump_0DDA:
	inc R6
jump_0DDB:
	mov A, @R1
jump_0DDC:
	movx @DPTR, A
	inc R1
	inc DPTR
	djnz R6, jump_0DDB
jump_0DE1:
	clr A
	movx @DPTR, A
	inc DPTR
	mov A, 82h
	anl A, #07h	;   7
	jnz jump_0DE1
	mov 66h, 82h
	mov 67h, 83h
	ajmp jump_0C84

fwd_0DF2_jump_0EC0:
	ajmp jump_0EC0

jump_0DF4:
	jnc fwd_0E41_jump_0D23
	jnb 29h.6, fwd_0E41_jump_0D23
	jb 2Ah.5, jump_0E26
	jb 2Ah.4, jump_0E43
	jb 2Ah.3, jump_0E20
	cjne R3, #10h, jump_0E15	;  16
	setb 29h.5
	mov C, 0E0h.0
	mov A, R4
	acall jump_0FC4
	jc jump_0E12
	cpl A
	anl 47h, A
	ret

jump_0E12:
	orl 47h, A
	ret

jump_0E15:
	mov 29h, #20h	;  32 ' '
	jnb 0E0h.0, jump_0E1F
	dec R3
	xrl 6Dh, #0FFh	; 255   -1 'ÿ'
jump_0E1F:
	ret

jump_0E20:
	jb 0E0h.0, jump_0E1F
	setb 28h.4
	ret

jump_0E26:
	orl 20h, #60h	;  96 '`'
	jb 0E0h.0, jump_0E33
	cjne @R1, #0FFh, jump_0E30	; 255   -1 'ÿ'
	ret

jump_0E30:
	inc @R1
	sjmp jump_0E38

jump_0E33:
	mov A, @R1
	jnz jump_0E37
	ret

jump_0E37:
	dec @R1
jump_0E38:
	mov 21h, #00h	;   0
	setb 25h.7
	mov 19h, #64h	; 100 'd'
	ret

fwd_0E41_jump_0D23:
	ajmp jump_0D23

jump_0E43:
	jnb 28h.1, fwd_0E41_jump_0D23
	jb 0E0h.0, jump_0E58
	jb 2Ah.0, jump_0EB5
	mov A, 66h
	add A, #08h	;   8
	mov 66h, A
	jnc jump_0E6D
	inc 67h
	sjmp jump_0E6D

jump_0E58:
	mov A, 66h
	add A, #0F8h	; 248   -8 'ø'
	mov 66h, A
	jc jump_0E6B
	mov A, 67h
	cjne A, 3Fh, jump_0E69
	mov 66h, #00h	;   0
	ret

jump_0E69:
	dec 67h
jump_0E6B:
	clr 2Ah.0
jump_0E6D:
	mov 82h, 66h
	mov 83h, 67h
	movx A, @DPTR
	jb 0E0h.7, jump_0EBA
	jnb 0E0h.6, jump_0E81
	jnb 0E0h.5, jump_0EB6
	mov 47h, #27h	;  39 '''
	ret

jump_0E81:
	jb 0E0h.5, jump_0E9D
	cjne A, #1Fh, jump_0E8B	;  31
	mov 47h, #4Fh	;  79 'O'
	ret

jump_0E8B:
	jnb 0E0h.4, jump_0E99
	jb 0E0h.3, jump_0E95
	mov 47h, #1Fh	;  31
	ret

jump_0E95:
	mov 47h, #3Fh	;  63 '?'
	ret

jump_0E99:
	mov 47h, #2Fh	;  47 '/'
	ret

jump_0E9D:
	jb 0E0h.4, jump_0EA4
	mov 47h, #0F7h	; 247   -9 '÷'
	ret

jump_0EA4:
	jb 0E0h.2, jump_0EAC
	mov 47h, #6Fh	; 111 'o'
	sjmp jump_0EAF

jump_0EAC:
	mov 47h, #5Fh	;  95 '_'
jump_0EAF:
	jnb 0E0h.1, jump_0EB5
	anl 47h, #0F7h	; 247   -9 '÷'
jump_0EB5:
	ret

jump_0EB6:
	mov 47h, #47h	;  71 'G'
	ret

jump_0EBA:
	mov 47h, #0Fh	;  15
	setb 2Ah.0
	ret

jump_0EC0:
	jb 0E0h.3, jump_0F0C
	jb 0E0h.2, jump_0EED
	jnb 28h.1, jump_0F07
	mov 26h, #00h	;   0
	jb 2Ah.2, jump_0ED4
	jb 28h.2, jump_0EE1
	sjmp jump_0F07

jump_0ED4:
	acall jump_0FCE
	acall jump_0803
	jnb 28h.1, jump_0F07
	setb 28h.2
	mov 1Fh, #0FFh	; 255   -1 'ÿ'
	mov A, R3
jump_0EE1:
	jb 0E0h.1, jump_0EE7
	setb 28h.3
	ret

jump_0EE7:
	setb 2Ah.3
	mov 29h, #40h	;  64 '@'
	ret

jump_0EED:
	anl 28h, #07h	;   7
	mov 26h, #00h	;   0
	jnb 2Ah.2, jump_0EF9
	acall jump_0FCE
	mov A, R3
jump_0EF9:
	jb 0E0h.1, jump_0F00
	clr 28h.2
	ajmp jump_0C84

jump_0F00:
	setb 2Ah.4
	mov 29h, #40h	;  64 '@'
	ajmp jump_0E6D

jump_0F07:
	anl 28h, #03h	;   3
fwd_0F0A_jump_0D23:
	ajmp jump_0D23

jump_0F0C:
	jnb 0E0h.1, jump_0F39
	mov 82h, 66h
	mov 83h, 67h
	jb 0E0h.2, jump_0F1E
	mov A, #40h	;  64 '@'
	movx @DPTR, A
	inc DPTR
	ajmp jump_0DE1

jump_0F1E:
	mov A, #83h	; 131 -125
	movx @DPTR, A
	mov 82h, #0FEh	; 254   -2 'þ'
	mov 83h, 3Eh
	mov A, 66h
	movx @DPTR, A
	inc DPTR
	mov A, 67h
	clr C
	subb A, 3Fh
	movx @DPTR, A
	lcall jump_0802
	jnb 28h.1, fwd_0F0A_jump_0D23
	ajmp jump_0C84

jump_0F39:
	jb 0E0h.2, jump_0F7A
	jnb 28h.1, jump_0F07
	mov A, 66h
	mov R4, A
	add A, #08h	;   8
	mov R2, A
	mov A, 67h
	mov R5, A
	addc A, #00h	;   0
	mov R3, A
	mov A, R5
	subb A, 77h
	jc jump_0F55
	mov A, R4
	subb A, 76h
	jnc fwd_0F0A_jump_0D23
jump_0F55:
	mov 82h, R2
	mov 83h, R3
	movx A, @DPTR
	mov 82h, R4
	mov 83h, R5
	movx @DPTR, A
	inc R4
	mov A, R4
	jnz jump_0F64
	inc R5
jump_0F64:
	inc R2
	mov A, R2
	jnz jump_0F69
	inc R3
jump_0F69:
	cjne A, 76h, jump_0F55
	mov A, R3
	cjne A, 77h, jump_0F55
	inc DPTR
	mov A, #83h	; 131 -125
	movx @DPTR, A
	mov 76h, R4
	mov 77h, R5
	sjmp jump_0FA8

jump_0F7A:
	mov A, 76h
	mov R2, A
	add A, #08h	;   8
	mov R4, A
	mov 76h, A
	mov A, 77h
	mov R3, A
	addc A, #00h	;   0
	mov R5, A
	mov 77h, A
jump_0F8A:
	mov 82h, R2
	mov 83h, R3
	movx A, @DPTR
	mov 82h, R4
	mov 83h, R5
	movx @DPTR, A
	mov A, R4
	dec R4
	jnz jump_0F99
	dec R5
jump_0F99:
	mov A, R2
	cjne A, 66h, jump_0FBE
	mov A, R3
	cjne A, 67h, jump_0FBD
	mov 82h, R2
	mov 83h, R3
	mov A, #20h	;  32 ' '
	movx @DPTR, A
jump_0FA8:
	mov 82h, #0FEh	; 254   -2 'þ'
	mov 83h, 3Eh
	mov A, 76h
	movx @DPTR, A
	inc DPTR
	mov A, 77h
jump_0FB4:
	clr C
	subb A, 3Fh
	movx @DPTR, A
	lcall jump_0802
	ajmp jump_0C84

jump_0FBD:
	mov A, R2
jump_0FBE:
	dec R2
	jnz jump_0F8A
	dec R3
	sjmp jump_0F8A

jump_0FC4:
	movc A, @A + PC
	ret

	ajmp jump_0802

	inc A
	inc R0
	jbc 24h.0, jump_100D
	sjmp jump_0FB4

; overlapping 1 byte(s)

org	0FCEh
jump_0FCE:
	mov A, 6Dh
	rl A
	mov 82h, A
	mov 83h, 3Eh
	movx A, @DPTR
	mov 66h, A
	inc DPTR
	movx A, @DPTR
	mov 67h, A
	ret

	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
jump_100D:
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A
	mov R7, A

end
